### ISSUE TITLE
executing autotest client tests from avocado 

### ISSUE THREAD

**Issue by kalshett** [avocado-framework/avocado-misc-tests#79]
This is regarding porting existing autotest client tests to avocado framework aka adding to misc tests bucket. I would like to hear pros/cons of executing autotest client tests directly through avocado run command, instead of porting autotest client tests to avocado misc test bucket.

Though I'm opening for discussion very late as many tests are already been ported, I thought its worth to hear from community on pros/cons of running autotest client tests using avocado run command.

Please feel free to add your comments.

**Comment by PraveenPenguin** [comment]
@kalshett  seems  me good idea so , but i think avocado a framework that having all supported library for avocado test (python lib)  and auto test is using different python lib. may be avocado wrapper can be extended to use autotest lib

**Comment by apahim** [comment]
@kalshett please send this message to the avocado-devel list, so you can have feedback from the avocado community, as you're intended to.
https://www.redhat.com/mailman/listinfo/avocado-devel

**Comment by clebergnu** [comment]
@kalshett we (the current Avocado team, and former Autotest developers), believe that Avocado is better than Autotest in many aspects, and since development is hapenning in Avocado, it tends to get even better.

Now, if you have many Autotest tests, and do not see any value in Avocado right now, you may just as well keep using Autotest, there's nothing wrong with that.

But yes, as suggested by @apahim, let's discuss porting/bridging ideas in the mailing list.  I'll close this issue so that the discussion happens there.
